Repository ca-cwds/design-system, pull requests merged in 2018-12, with the labels that each got.

#277 fix(www): no boder radius for doc-only components
  apps/www/src/components/MDXComponentProviderMappings.jsx
Labels: docs

#279 fix(components): Add IconButton
  libs/components/src/IconButton/IconButton.jsx
  libs/components/src/IconButton/IconButton.test.js
  libs/components/src/IconButton/index.js
  libs/components/src/index.js
Labels: components, enhancement

#285 fix(www): remove unvalidated search modal
  apps/www/src/modules/components/RouteUtils.jsx
Labels: docs

#284 CODE-90 config eslint and move prettier to eslint rules
  .eslintignore
  .eslintrc.js
  .prettierrc
  .vscode/settings.json
  package.json
  yarn.lock
Labels: build, tech debt

#286 fix(www): update general DS article content
  apps/www/src/modules/components/modules/Components.mdx
  apps/www/src/modules/core-style/CoreStyle.jsx
  apps/www/src/modules/core-style/CoreStyle.mdx
  apps/www/src/modules/core-style/modules/FunctionalCss.mdx
  apps/www/src/modules/core-style/modules/GridSystem.mdx
  apps/www/src/modules/core-style/modules/Tone.mdx
  apps/www/src/modules/core-style/modules/Typography.mdx
Labels: docs

#287 fix(www): update docs for Avatar, Alert, Button
  apps/www/src/modules/components/modules/Alert/Alert.mdx
  apps/www/src/modules/components/modules/Alert/DismissableAlert.example.jsx
  apps/www/src/modules/components/modules/Avatar/Avatar.mdx
  apps/www/src/modules/components/modules/Button/Button.mdx
Labels: docs

#289 fix: restore image for Figure doc-only component
  apps/www/src/modules/components/RouteUtils.jsx
  apps/www/src/modules/components/modules/Card/LoadingCardExample.jsx
  apps/www/src/modules/components/modules/image.jpg
Labels: docs

#292 fix(www): update Icon docs
  apps/www/package.json
  apps/www/src/macros/docgen-composed.macro.js
  apps/www/src/modules/components/modules/Alert/DismissableAlert.example.jsx
  apps/www/src/modules/components/modules/Icon/Icon.mdx
  apps/www/src/modules/components/modules/ReactDogenInfo.js
  libs/icons/src/Icon.jsx
  libs/icons/src/fontawesome.props
  yarn.lock
Labels: docs

#295 fix(build): tidy npm run scripts
  package.json
Labels: build, tech debt

#302 fix: incorrect rollup format spec
  libs/datagrid/rollup.config.js
Labels: tech debt

#316 fix(tech): minor eslint config changes
  .eslintignore
  .eslintrc.js
Labels: bug, tech debt

#317 fix: relax lints
  .eslintrc.js
Labels: tech debt

#331 resolve lint errors
  .eslintrc.js
  apps/www/src/components/MDXComponentProviderMappings.jsx
  apps/www/src/macros/docgen-composed.macro.js
  apps/www/src/macros/meta-info.macro.js
  apps/www/src/modules/components/SearchWizard.jsx
  apps/www/src/modules/labs/views/CardsPage/AsyncCardExample.jsx
  apps/www/src/modules/labs/views/CardsPage/CardsForCANS.jsx
  apps/www/src/modules/labs/views/CardsPage/CardsWithSections.jsx
  apps/www/src/modules/labs/views/CardsPage/MultiScopeCards.jsx
  apps/www/src/modules/labs/views/DataGridsPage/AdvancedSearch/AdvancedSearch.jsx
  apps/www/src/modules/labs/views/DataGridsPage/AdvancedSearch/mockService.js
  apps/www/src/modules/labs/views/DataGridsPage/StarWars/StarWarsDataGrid.jsx
  apps/www/src/modules/labs/views/FormsPage/examples/ContactsForm/FormContacts.jsx
  libs/components/rollup.config.js
  libs/components/src/Alert/Alert.stories.js
  libs/components/src/Alert/AlertUncontrolled.stories.js
  libs/components/src/Alert/index.js
  libs/components/src/AppBar/AppBar.jsx
  libs/components/src/AppBar/AppBar.stories.js
  libs/components/src/Avatar/Avatar.stories.js
  libs/components/src/BreadcrumbTrail/BreadcrumbTrail.jsx
  libs/components/src/Field/Field.jsx
  libs/components/src/Field/Field.stories.js
  libs/components/src/Field/Field.test.js
  libs/components/src/InfoTip/InfoTip.stories.js
  libs/components/src/JumpNav/JumpNav.jsx
  libs/components/src/Layouts/Banner/Banner.jsx
  libs/components/src/Layouts/Body/Body.jsx
  libs/components/src/Legend/Legend.jsx
  libs/components/src/Logo/Logo.jsx
  libs/components/src/Logo/Logo.stories.js
  libs/components/src/PageHeader/PageHeader.jsx
  libs/components/src/PageHeader/PageHeader.stories.js
  libs/components/src/RadioGroup/RadioGroup.js
  libs/components/src/Rolodex/Rolodex.jsx
  libs/components/src/Rolodex/RolodexPanel.jsx
  libs/components/src/utils/index.js
  libs/components/src/utils/utils.jsx
  libs/components/src/utils/utils.test.module.scss
  libs/datagrid/src/DataGrid.jsx
  libs/datagrid/src/DataGrid.stories.js
  libs/datagrid/src/DataGridConfig.jsx
  libs/datagrid/src/Pagination.jsx
  libs/datagrid/src/__tests__/DataGrid.test.js
  libs/reactstrap/src/Dropdown.jsx
  libs/reactstrap/src/DropdownItem.jsx
Labels: tech debt

#334 fix: mdx syntax err
  apps/www/src/modules/components/modules/Alert/Alert.mdx
Labels: bug, docs

#337 docs: drop alpha dist tag from getting started
  README.md
Labels: docs

#345 fix(tech): consistent filename casing for Infotips
  apps/www/src/modules/components/modules/InfoTip/index.js
  apps/www/src/modules/components/modules/Infotip/Infotip.mdx
  apps/www/src/modules/components/modules/Infotip/examples/InfotipExample.jsx
  apps/www/src/modules/components/modules/Infotip/examples/UncontrolledInfotipExample.jsx
  apps/www/src/modules/components/modules/Infotip/examples/index.js
  apps/www/src/modules/components/modules/Infotip/index.js
  libs/components/src/Infotip/Infotip.jsx
  libs/components/src/Infotip/Infotip.module.scss
  libs/components/src/Infotip/Infotip.stories.js
  libs/components/src/Infotip/Infotip.test.js
  libs/components/src/Infotip/README.md
  libs/components/src/Infotip/UncontrolledInfotip.jsx
  libs/components/src/Infotip/UncontrolledInfotip.test.js
  libs/components/src/Infotip/index.js
Labels: tech debt

#346 fix(datagrid): fix datagrid pagination flex layout bug
  libs/datagrid/src/DataGrid.module.scss
Labels: bug
