Repository ca-cwds/design-system, pull requests merged in 2019-04, with the labels that each got.

#521 feat(forms, docs): Add docs Select/dropdown
  apps/www/src/modules/components/articles/Forms/FormsSelectArticle.mdx
  apps/www/src/modules/components/articles/Forms/examples/SimpleSelectExample.jsx
  apps/www/src/modules/components/articles/Menu/MenuPage.mdx
  apps/www/src/modules/components/routes.js
  apps/www/src/modules/labs/views/FormsPage/examples/ContactsForm/FormContacts.jsx
  apps/www/src/modules/labs/views/FormsPage/examples/NChoose1/NChoose1.jsx
  apps/www/src/modules/labs/views/FormsPage/examples/NChooseK/NChooseK.jsx
  libs/components/src/Select/README.md
  libs/components/src/Select/Select.jsx
  libs/components/src/Select/Select.module.scss
  libs/components/src/Select/Select.stories.js
  libs/components/src/Select/Select.test.js
  libs/components/src/Select/index.js
  libs/components/src/index.js
  libs/forms/src/index.ts
Labels: docs, next

#523 chore: add badges to main README
  README.md
Labels: release

#528 fix(components): Fix missing scss modules
  libs/components/src/index.js
Labels: release

#538 fix(component): Ellipsis menu not showing up when integrating with Datagrid
  apps/www/src/modules/components/articles/DataGrid/examples/CarsDataGridSmall.jsx
  libs/cares/src/Menu/Menu.jsx
  libs/core/scss/modules/_dropdown.scss
Labels: bug

#544 fix(core): revert PageHeader solid to gradient
  libs/cares/src/Layouts/Layout.module.scss
Labels: release

#546 fix(cares,core,docs): fix Button style
  apps/www/src/modules/components/articles/Button/Button.splat.jsx
  apps/www/src/modules/components/routes.js
  libs/cares/src/Button/Button.jsx
  libs/cares/src/Button/Button.module.scss
  libs/core/scss/modules/_buttons.scss
Labels: release

#557 chore(www): add Alert splats
  apps/www/src/modules/components/articles/Alert/Alert.splat.jsx
  apps/www/src/modules/components/routes.js
Labels: release

#567 chore: trigger release
  README.md
Labels: release

#568 fix(cares,core): solid background in PageHeader
  libs/cares/src/Layouts/Layout.module.scss
  libs/core/scss/_custom.scss
Labels: release

#577 chore: release
  README.md
Labels: release

#596 fix(core): update $warning color
  libs/core/scss/_custom.scss
Labels: release

#603 fix(cares): fix react-popper missing Arrow
  libs/cares/package.json
Labels: release
