Repository ca-cwds/design-system, pull requests merged in 2019-03, with the labels that each got.

#432 feat(components): Add messaging area to page template
  libs/components/src/Layouts/Body/Body.jsx
  libs/components/src/Layouts/Body/Body.test.js
  libs/components/src/Layouts/Layout.module.scss
  libs/components/src/Layouts/Page/Page.jsx
  libs/components/src/Layouts/Page/Page.test.js
  libs/components/src/index.js
Labels: next

#434 fix(components): remove broken export
  libs/components/src/index.js
Labels: build, next

#433 fix(docs): add contributing
  CONTRIBUTING.md
Labels: docs, next

#437 Message Area Placeholder Demo
  apps/www/src/App.js
  apps/www/src/demos/MesssageArea/MessageArea.jsx
  apps/www/src/demos/MesssageArea/Sidenav.jsx
  apps/www/src/demos/MesssageArea/index.js
  apps/www/src/demos/ReassessmentForm/index.js
Labels: next

#438 fix(components): Fix react-select to open top when no space bottom.
  libs/datagrid/src/Pagination.jsx
Labels: bug, next

#436 fix(components): fix Avatar alignment in UserMenu
  libs/components/src/Menu/UserMenu.jsx
Labels: next

#435 fix(components): fix a11y kebab menu
  libs/components/src/Menu/Menu.jsx
  libs/components/src/Menu/Menu.test.js
Labels: next

#439 fix(core): fix Breadcrumb horizontal scroll
  libs/components/src/Layouts/Banner/Banner.jsx
  libs/core/scss/bootstrap-cares.module.scss
  libs/core/scss/modules/_breadcrumb.scss
Labels: next

#440 fix(build): fix prerelease routine
  package.json
Labels: build

#441 fix(build): open coverage with `yarn coverage`
  package.json
Labels: build

#415 feat(forms): Add forms package
  libs/forms/README.md
  libs/forms/ambient.d.ts
  libs/forms/jest.config.js
  libs/forms/package.json
  libs/forms/rollup.config.js
  libs/forms/src/.babelrc
  libs/forms/src/CheckboxBank.tsx
  libs/forms/src/RadioGroup.tsx
  libs/forms/src/SelectList.module.scss
  libs/forms/src/SelectList.test.tsx
  libs/forms/src/SelectList.tsx
  libs/forms/src/index.ts
  libs/forms/src/types.ts
  libs/forms/tsconfig.json
  scripts/jest-utils.js
  yarn.lock
Labels: components

#449 fix(build): exact versions for inter-package deps
  package.json
Labels: build

#450 chore(components): fix lints
  libs/components/src/CollapsibleCard/CollapsibleCard.jsx
  libs/components/src/Menu/Menu.jsx
  libs/components/src/PageActions/PageActions.jsx
  libs/components/src/Placeholder/Placeholder.jsx
  libs/components/src/Rolodex/Rolodex.jsx
  libs/components/src/Rolodex/RolodexHeader.jsx
  libs/docs/src/AnchorLink/AnchorLink.jsx
Labels: build, components

#458 FIT-475 - Create Master Pipeline for Component Library: initial pipeline
  jenkinsfile.groovy
Labels: patch

#459 FIT-475 - Create Master Pipeline for Component Library
  jenkinsfile.groovy
Labels: patch

#460 FIT-475 Create Master Pipeline for Component Library
  jenkinsfile.groovy
Labels: patch

#457 chore(docs): Toggle full screen
  libs/docs/package.json
  libs/docs/src/Articles/Article.jsx
  libs/docs/src/Articles/Article.test.js
Labels: docs, patch

#461 fix(datagrid): Omit Pagination for small client-side paginated collections
  apps/www/src/demos/ReassessmentForm/dummydata.js
  apps/www/src/modules/components/articles/DataGrid/SimpleDataGrid.mdx
  apps/www/src/modules/components/articles/DataGrid/examples/CarsDataGridSmall.jsx
  libs/core/scss/_base.scss
  libs/core/scss/_mixins.scss
  libs/core/scss/mixins/_scroll.scss
  libs/core/scss/modules/_breadcrumb.scss
  libs/datagrid/src/DataGrid.module.scss
  libs/datagrid/src/DataGridConfig.jsx
  libs/datagrid/src/Pagination.jsx
  libs/datagrid/src/Pagination.test.js
Labels: patch

#452 fix(docs): fix example src for Menu demo
  apps/www/src/modules/components/articles/Menu/examples/index.js
Labels: docs, patch

#462 fix(modal, www): Modal update CL-103
  apps/www/src/modules/components/articles/Modal/Modal.example.jsx
  apps/www/src/modules/components/articles/Modal/Modal.mdx
  apps/www/src/modules/components/articles/Modal/examples/AlertModalExample.jsx
  apps/www/src/modules/components/articles/Modal/examples/BasicModalExample.jsx
  apps/www/src/modules/components/articles/Modal/examples/ScrollingModalExample.jsx
  apps/www/src/modules/components/articles/Modal/examples/SizeModalExample.jsx
  apps/www/src/modules/components/articles/Modal/examples/index.js
  libs/components/src/Alert/Alert.jsx
  libs/reactstrap/src/Modal.jsx
  libs/reactstrap/src/ModalHeader.jsx
  libs/reactstrap/src/index.js
Labels: docs, patch

#463 chore(build): PR pipeline, docker beginnings
  .dockerignore
  jenkinsfile.groovy
Labels: build

#469 fix(build): Add master build pipeline
  jenkinsfile.groovy
Labels: build

#468 fix(build): typescript fixes for build pipeline
  .gitignore
  libs/forms/jest.config.js
  libs/forms/src/index.test.ts
  package.json
  yarn.lock
Labels: build

#481 chore(www): update CRA react-scripts
  apps/www/package.json
Labels: docs

#478 fix CRA start from monorepo root
  package.json
Labels: build

#476 fix(build): Use module-resolver for style imports
  babel.config.js
  libs/components/package.json
  libs/core/package.json
  libs/datagrid/package.json
  libs/docs/package.json
  libs/forms/package.json
  libs/icons/package.json
  libs/reactstrap/package.json
  package.json
  yarn.lock
Labels: build

#486 fix(docs): Demo show toggles
  apps/www/package.json
  apps/www/src/App.js
  apps/www/src/demos/ToggleDemos.js
Labels: docs

#485 chore: sort guide site Article sidebar links
  libs/docs/package.json
  libs/docs/src/Articles/article-router.js
  libs/docs/src/Articles/article-router.test.js
Labels: docs

#488 chore(ci): Automate publishing to npm
  jenkinsfile.groovy
  package.json
Labels: debug, release

#489 chore(ci): fix automate relase
  jenkinsfile.groovy
Labels: release

#493 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#494 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#495 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#496 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#497 rebase out later
  jenkinsfile.groovy
Labels: release

#498 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#499 fix(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#500 fix(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#501 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#502 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#503 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#504 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#505 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#506 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#507 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#508 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#510 chore(ci): fix automate release
  jenkinsfile.groovy
Labels: release

#509 feat(components): Added CaresButton component.
  apps/www/src/modules/components/articles/Button/Button.mdx
  libs/components/src/CaresButton/CaresButton.jsx
  libs/components/src/CaresButton/CaresButton.test.js
  libs/components/src/CaresButton/index.js
  libs/components/src/index.js
  libs/components/src/index.test.js
Labels: components

#513 fix(forms): add type defs
  libs/forms/package.json
Labels: build
