Repository ca-cwds/design-system, pull requests merged in 2019-02, with the labels that each got.

#395 update rails_app
  apps/rails_app/Gemfile.lock
  apps/rails_app/app/controllers/components_controller.rb
  apps/rails_app/app/helpers/components_helper.rb
  apps/rails_app/app/javascript/components/Components.jsx
  apps/rails_app/app/javascript/components/examples/Alert.jsx
  apps/rails_app/app/javascript/components/examples/Badge.jsx
  apps/rails_app/app/javascript/components/examples/Button.jsx
  apps/rails_app/app/javascript/components/examples/index.js
  apps/rails_app/app/javascript/components/index.js
  apps/rails_app/app/javascript/main/Main.jsx
  apps/rails_app/app/javascript/packs/components.js
  apps/rails_app/app/views/components/index.html.erb
  apps/rails_app/app/views/components/show.html.erb
  apps/rails_app/config/routes.rb
  apps/rails_app/package.json
  yarn.lock
Labels: next

#400 fix missing CodeBlock import in DataGrid docs
  apps/www/src/modules/components/modules/DataGrid/SimpleDataGrid.mdx
Labels: next

#402 Body takes nodes OR components
  libs/components/src/Layouts/Body/Body.jsx
  libs/components/src/Layouts/Body/Body.test.js
Labels: components

#407 fix clean libs npm script name
  package.json
Labels: next

#408 fix(tech): Transforms cwds pkg imports in Jest tests
  scripts/jest-utils.js
Labels: next

#409 fix(www) refactor Page template component API
  apps/www/src/modules/components/articles/Page/Page.mdx
  apps/www/src/modules/components/articles/ReactDogenInfo.js
  libs/components/src/Layouts/Page/Page.jsx
  libs/components/src/Layouts/Page/Page.props
Labels: next

#417 fix(www): update Breadcrumb, BreadcrumbItem docs
  apps/www/src/modules/components/articles/BreadcrumbItem/BreadcrumbItem.mdx
  apps/www/src/modules/components/articles/Breadcrumbs/Breadcrumbs.mdx
  apps/www/src/modules/components/articles/ReactDogenInfo.js
  apps/www/src/modules/components/routes.js
Labels: next

#418 feat(components): add Tile component
  apps/www/src/modules/components/articles/ReactDogenInfo.js
  apps/www/src/modules/components/articles/Tile/Tile.mdx
  apps/www/src/modules/components/articles/Tile/TileExample.jsx
  apps/www/src/modules/components/articles/Tile/TileGroupExample.jsx
  apps/www/src/modules/components/routes.js
  libs/components/src/Menu/Menu.jsx
  libs/components/src/Menu/Menu.test.js
  libs/components/src/Tile/Tile.jsx
  libs/components/src/Tile/Tile.module.scss
  libs/components/src/Tile/Tile.test.js
  libs/components/src/Tile/TileGroup.jsx
  libs/components/src/Tile/TileGroup.test.js
  libs/components/src/Tile/TilePlaceholder.jsx
  libs/components/src/Tile/TilePlaceholder.test.js
  libs/components/src/Tile/index.js
  libs/components/src/Tile/index.test.js
  libs/components/src/index.js
  libs/reactstrap/src/index.js
Labels: next

#416 fix(www, components):CL-30 remove todo in doc pages and deprecate some components
  apps/www/src/modules/components/articles/Alert/Alert.example.jsx
  apps/www/src/modules/components/articles/Alert/Alert.mdx
  apps/www/src/modules/components/articles/Badge/Badge.example.jsx
  apps/www/src/modules/components/articles/Badge/Badge.mdx
  apps/www/src/modules/components/articles/Button/Button.mdx
  apps/www/src/modules/components/articles/ButtonGroup/ButtonGroup.mdx
  apps/www/src/modules/components/articles/Card/Loading.mdx
  apps/www/src/modules/components/articles/DataGrid/BasicSearchDataGrid.mdx
  apps/www/src/modules/components/articles/DataGrid/DataGrid.mdx
  apps/www/src/modules/components/articles/Grid/Grid.mdx
  apps/www/src/modules/components/articles/Page/Page.mdx
  apps/www/src/modules/home/Home.jsx
  apps/www/src/modules/labs/views/FormsPage/examples/ContactsForm/FormContacts.jsx
  apps/www/src/modules/labs/views/FormsPage/examples/NChoose1/NChoose1.jsx
  apps/www/src/modules/labs/views/FormsPage/examples/NChooseK/NChooseK.jsx
  apps/www/src/modules/layouts/Layouts.jsx
  apps/www/src/modules/layouts/index.js
  apps/www/src/modules/layouts/media/centered-content.jpg
  apps/www/src/modules/layouts/media/header-elems.jpg
  apps/www/src/modules/layouts/media/header-main.jpg
  apps/www/src/modules/layouts/media/layout13.jpg
  apps/www/src/modules/layouts/media/layout31.jpg
  apps/www/src/modules/layouts/views/About.jsx
  apps/www/src/modules/layouts/views/BasicContent.jsx
  apps/www/src/modules/layouts/views/Dashboard.jsx
  apps/www/src/modules/layouts/views/Dashboard.mdx
  apps/www/src/modules/layouts/views/JumpNav.mdx
  apps/www/src/modules/layouts/views/LongJump.jsx
  apps/www/src/modules/layouts/views/PageComposition.mdx
  apps/www/src/modules/layouts/views/RouteNest.jsx
  apps/www/src/modules/layouts/views/SubRoutes.mdx
  libs/components/src/CheckboxBank/CheckboxBank.jsx
  libs/components/src/CheckboxBank/CheckboxBank.stories.js
  libs/components/src/CheckboxBank/CheckboxBank.test.js
  libs/components/src/CheckboxBank/index.js
  libs/components/src/Legend/Legend.jsx
  libs/components/src/Legend/index.js
  libs/components/src/RadioGroup/RadioGroup.js
  libs/components/src/RadioGroup/RadioGroup.js.good
  libs/components/src/RadioGroup/RadioGroup.tsx
  libs/components/src/RadioGroup/index.js
  libs/components/src/RadioGroup/types.js
  libs/components/src/RadioGroup/types.ts
  libs/components/src/index.js
Labels: next

#419 fix(docs): Content_Updates
  apps/www/src/App.js
  apps/www/src/modules/about-cares/AboutCares.jsx
  apps/www/src/modules/about-cares/AboutCares.mdx
  apps/www/src/modules/about-cares/index.js
  apps/www/src/modules/components/articles/Alert/Alert.mdx
  apps/www/src/modules/components/articles/Components.mdx
  apps/www/src/modules/core-style/CoreStyle.jsx
  apps/www/src/modules/home/Home.jsx
Labels: next

#422 feat(components): consume context in leaf components
  apps/www/src/config.js
  apps/www/src/modules/components/articles/CaresProvider/CaresProvider.mdx
  apps/www/src/modules/components/articles/ReactDogenInfo.js
  libs/components/src/AppBar/AppBar.jsx
  libs/components/src/AppBar/AppBar.test.js
  libs/components/src/AppBar/index.js
  libs/components/src/CaresContext/CaresProvider.props
  libs/components/src/CaresContext/defaults/Brand.jsx
  libs/components/src/CaresContext/defaults/UserMenu.jsx
  libs/components/src/CaresContext/defaults/index.js
  libs/components/src/CaresContext/index.jsx
  libs/components/src/index.js
  libs/components/src/utils/index.js
  libs/components/src/utils/renderOne.js
Labels: next

#424 fix: Update main README
  README.md
Labels: next

#425 Update breadcrumb overflow styles
  libs/components/src/Layouts/Layout.module.scss
Labels: bug

#431 feat(components): Added footer component.
  libs/components/src/Layouts/Footer/Footer.jsx
  libs/components/src/Layouts/Footer/Footer.test.js
  libs/components/src/Layouts/Footer/index.js
  libs/components/src/Layouts/Layout.module.scss
  libs/components/src/Layouts/Page/Page.jsx
  libs/components/src/Layouts/Page/Page.test.js
Labels: components, next

#429 fix(www): Added article sub component data grid
  apps/www/src/modules/components/articles/DataGrid/SubcomponentDataGrid.mdx
  apps/www/src/modules/components/articles/DataGrid/examples/AggregationDataGrid.jsx
  apps/www/src/modules/components/articles/DataGrid/examples/SubcomponentDataGrid.jsx
  apps/www/src/modules/components/routes.js
Labels: docs, next
